inputSet:
  name: Build_project_5_peer_review_application_peerreviewapp_team5_1689139485030-pr-trigger-input-set
  identifier: Build_project_5_peer_review_application_peerreviewapp_team5_1689139485030prtriggerinputset
  orgIdentifier: default
  projectIdentifier: default_project
  pipeline:
    identifier: Build_project_5_peer_review_application_peerreviewapp_team5_1689139485030
    properties:
      ci:
        codebase:
          build:
            type: PR
            spec:
              number: <+trigger.prNumber>
