pipeline:
  identifier: Build_project_5_peer_review_application_peerreviewapp_team5_1689139485030
  name: Build project-5-peer-review-application-peerreviewapp_team5
  orgIdentifier: default
  projectIdentifier: default_project
  properties:
    ci:
      codebase:
        build: <+input>
        connectorRef: account.Github
        repoName: UBCO-COSC-499-Summer-2023/project-5-peer-review-application-peerreviewapp_team5
  stages:
    - stage:
        identifier: build
        name: build
        spec:
          cloneCodebase: true
          execution:
            steps:
              - step:
                  identifier: echo
                  name: "Start Up Docker Containers "
                  spec:
                    shell: Sh
                    command: docker compose up -d
                  timeout: ""
                  type: Run
          platform:
            arch: Amd64
            os: Linux
          runtime:
            spec: {}
            type: Cloud
        type: CI
