version : "3.9"

services:
    backend:
        build: ./
        image: mvc_service
        ports:
            - "80:3001" ## map local 8080 to containor port 80
        restart: always
        environment:
            port: 3001
            database_ip: "localhost"
            database_user: "root"
            database_password: "password"
            database_name: "test_Database"
        
